// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login_status.proto

package com_bc_login_protobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestUserLoginLoginWay int32

const (
	RequestUserLogin_MESSAGE  RequestUserLoginLoginWay = 0
	RequestUserLogin_PASSWORD RequestUserLoginLoginWay = 2
)

var RequestUserLoginLoginWay_name = map[int32]string{
	0: "MESSAGE",
	2: "PASSWORD",
}

var RequestUserLoginLoginWay_value = map[string]int32{
	"MESSAGE":  0,
	"PASSWORD": 2,
}

func (x RequestUserLoginLoginWay) String() string {
	return proto.EnumName(RequestUserLoginLoginWay_name, int32(x))
}

func (RequestUserLoginLoginWay) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_113c80b8ac6652e8, []int{3, 0}
}

//部分接口公共字段
type UserToken struct {
	LoginId              string   `protobuf:"bytes,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_113c80b8ac6652e8, []int{0}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

func (m *UserToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//获取验证码
type RequestVerificationCode struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVerificationCode) Reset()         { *m = RequestVerificationCode{} }
func (m *RequestVerificationCode) String() string { return proto.CompactTextString(m) }
func (*RequestVerificationCode) ProtoMessage()    {}
func (*RequestVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_113c80b8ac6652e8, []int{1}
}

func (m *RequestVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVerificationCode.Unmarshal(m, b)
}
func (m *RequestVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVerificationCode.Marshal(b, m, deterministic)
}
func (m *RequestVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVerificationCode.Merge(m, src)
}
func (m *RequestVerificationCode) XXX_Size() int {
	return xxx_messageInfo_RequestVerificationCode.Size(m)
}
func (m *RequestVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVerificationCode proto.InternalMessageInfo

func (m *RequestVerificationCode) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

//获取验证码：服务器返回状态码
type ResponseVerificationCode struct {
	Code                 *ResponseCode `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseVerificationCode) Reset()         { *m = ResponseVerificationCode{} }
func (m *ResponseVerificationCode) String() string { return proto.CompactTextString(m) }
func (*ResponseVerificationCode) ProtoMessage()    {}
func (*ResponseVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_113c80b8ac6652e8, []int{2}
}

func (m *ResponseVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseVerificationCode.Unmarshal(m, b)
}
func (m *ResponseVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseVerificationCode.Marshal(b, m, deterministic)
}
func (m *ResponseVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseVerificationCode.Merge(m, src)
}
func (m *ResponseVerificationCode) XXX_Size() int {
	return xxx_messageInfo_ResponseVerificationCode.Size(m)
}
func (m *ResponseVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseVerificationCode proto.InternalMessageInfo

func (m *ResponseVerificationCode) GetCode() *ResponseCode {
	if m != nil {
		return m.Code
	}
	return nil
}

type RequestUserLogin struct {
	PhoneNumber          string                   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Type                 RequestUserLoginLoginWay `protobuf:"varint,2,opt,name=type,proto3,enum=com.bc.login.protobuffer.RequestUserLoginLoginWay" json:"type,omitempty"`
	Code                 string                   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RequestUserLogin) Reset()         { *m = RequestUserLogin{} }
func (m *RequestUserLogin) String() string { return proto.CompactTextString(m) }
func (*RequestUserLogin) ProtoMessage()    {}
func (*RequestUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_113c80b8ac6652e8, []int{3}
}

func (m *RequestUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUserLogin.Unmarshal(m, b)
}
func (m *RequestUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUserLogin.Marshal(b, m, deterministic)
}
func (m *RequestUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUserLogin.Merge(m, src)
}
func (m *RequestUserLogin) XXX_Size() int {
	return xxx_messageInfo_RequestUserLogin.Size(m)
}
func (m *RequestUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUserLogin proto.InternalMessageInfo

func (m *RequestUserLogin) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *RequestUserLogin) GetType() RequestUserLoginLoginWay {
	if m != nil {
		return m.Type
	}
	return RequestUserLogin_MESSAGE
}

func (m *RequestUserLogin) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ResponseUserLogin struct {
	Code                 *ResponseCode `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Id                   string        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseUserLogin) Reset()         { *m = ResponseUserLogin{} }
func (m *ResponseUserLogin) String() string { return proto.CompactTextString(m) }
func (*ResponseUserLogin) ProtoMessage()    {}
func (*ResponseUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_113c80b8ac6652e8, []int{4}
}

func (m *ResponseUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUserLogin.Unmarshal(m, b)
}
func (m *ResponseUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUserLogin.Marshal(b, m, deterministic)
}
func (m *ResponseUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUserLogin.Merge(m, src)
}
func (m *ResponseUserLogin) XXX_Size() int {
	return xxx_messageInfo_ResponseUserLogin.Size(m)
}
func (m *ResponseUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUserLogin proto.InternalMessageInfo

func (m *ResponseUserLogin) GetCode() *ResponseCode {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ResponseUserLogin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("com.bc.login.protobuffer.RequestUserLoginLoginWay", RequestUserLoginLoginWay_name, RequestUserLoginLoginWay_value)
	proto.RegisterType((*UserToken)(nil), "com.bc.login.protobuffer.user_token")
	proto.RegisterType((*RequestVerificationCode)(nil), "com.bc.login.protobuffer.request_verification_code")
	proto.RegisterType((*ResponseVerificationCode)(nil), "com.bc.login.protobuffer.response_verification_code")
	proto.RegisterType((*RequestUserLogin)(nil), "com.bc.login.protobuffer.request_user_login")
	proto.RegisterType((*ResponseUserLogin)(nil), "com.bc.login.protobuffer.response_user_login")
}

func init() { proto.RegisterFile("login_status.proto", fileDescriptor_113c80b8ac6652e8) }

var fileDescriptor_113c80b8ac6652e8 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x6d, 0xac, 0xb6, 0x9d, 0x96, 0x52, 0xa6, 0x1e, 0xda, 0x9e, 0x34, 0x07, 0x11, 0x0f,
	0x7b, 0xa8, 0xe0, 0xcd, 0x42, 0xc1, 0x22, 0x0a, 0xfe, 0x21, 0x39, 0x78, 0x11, 0x42, 0x93, 0x4c,
	0x75, 0xb1, 0xcd, 0xc6, 0xdd, 0x8d, 0xd2, 0x4f, 0xe7, 0x57, 0x93, 0xce, 0xa6, 0xa5, 0xa0, 0x82,
	0xe0, 0x29, 0xcc, 0xdb, 0x79, 0x6f, 0xe6, 0x37, 0x01, 0x9c, 0xab, 0x67, 0x99, 0x45, 0xc6, 0x4e,
	0x6d, 0x61, 0x44, 0xae, 0x95, 0x55, 0xd8, 0x4b, 0xd4, 0x42, 0xc4, 0x89, 0xe0, 0x27, 0xa7, 0xc5,
	0xc5, 0x6c, 0x46, 0x7a, 0xd0, 0xe5, 0x22, 0x51, 0xf3, 0x28, 0x51, 0x29, 0xb9, 0x27, 0xff, 0x02,
	0xa0, 0x30, 0xa4, 0x23, 0xab, 0x5e, 0x29, 0xc3, 0x3e, 0xd4, 0x5d, 0xa4, 0x4c, 0x7b, 0x95, 0xc3,
	0xca, 0x49, 0x23, 0xa8, 0x71, 0x7d, 0x9d, 0xe2, 0x01, 0xec, 0x71, 0x4f, 0xcf, 0x63, 0xdd, 0x15,
	0xfe, 0x08, 0xfa, 0x9a, 0xde, 0x0a, 0x32, 0x36, 0x7a, 0x27, 0x2d, 0x67, 0x32, 0x99, 0x5a, 0xa9,
	0x32, 0x9e, 0x80, 0x47, 0xd0, 0xca, 0x5f, 0x54, 0x46, 0x51, 0x56, 0x2c, 0x62, 0xd2, 0x65, 0x62,
	0x93, 0xb5, 0x3b, 0x96, 0xfc, 0x27, 0x18, 0x68, 0x32, 0xb9, 0xca, 0x0c, 0xfd, 0x10, 0x30, 0x82,
	0xea, 0xea, 0xcb, 0xc6, 0xe6, 0xf0, 0x54, 0x94, 0x68, 0x6b, 0x8e, 0x6d, 0x3a, 0xb1, 0x89, 0x59,
	0x39, 0x02, 0xf6, 0xf9, 0x9f, 0x15, 0xc0, 0xf5, 0x7a, 0x4c, 0xc9, 0x30, 0x7f, 0xd8, 0x0b, 0x6f,
	0xa0, 0x6a, 0x97, 0x39, 0x31, 0x6c, 0x7b, 0x78, 0x2e, 0x7e, 0x3b, 0xaa, 0xf8, 0x1e, 0xef, 0x9a,
	0xa2, 0x8f, 0xe9, 0x32, 0xe0, 0x0c, 0xc4, 0x92, 0x62, 0x97, 0xc7, 0xb8, 0xcd, 0x8e, 0xa1, 0xb1,
	0x69, 0xc3, 0x26, 0xd4, 0x6e, 0x27, 0x61, 0x38, 0xbe, 0x9a, 0x74, 0x76, 0xb0, 0x05, 0xf5, 0x87,
	0x71, 0x18, 0x3e, 0xde, 0x07, 0x97, 0x1d, 0xcf, 0x27, 0xe8, 0x6e, 0xc0, 0xb6, 0x08, 0xfe, 0x79,
	0x18, 0x6c, 0x83, 0x27, 0xd3, 0xf2, 0x4f, 0x7a, 0x32, 0x8d, 0xf7, 0xd9, 0x70, 0xf6, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x71, 0xf7, 0xf1, 0x09, 0x51, 0x02, 0x00, 0x00,
}
