// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol_code.proto

package com_bc_protocol_protobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCodeResCode int32

const (
	ResponseCode_UNKNOWN      ResponseCodeResCode = 0
	ResponseCode_SUCESS       ResponseCodeResCode = 200
	ResponseCode_UNAUTHORIZED ResponseCodeResCode = 401
)

var ResponseCodeResCode_name = map[int32]string{
	0:   "UNKNOWN",
	200: "SUCESS",
	401: "UNAUTHORIZED",
}

var ResponseCodeResCode_value = map[string]int32{
	"UNKNOWN":      0,
	"SUCESS":       200,
	"UNAUTHORIZED": 401,
}

func (x ResponseCodeResCode) String() string {
	return proto.EnumName(ResponseCodeResCode_name, int32(x))
}

func (ResponseCodeResCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cbb99ad2cb96e3c2, []int{0, 0}
}

type ResponseCode struct {
	Code                 ResponseCodeResCode `protobuf:"varint,1,opt,name=code,proto3,enum=com.bc.protocol.protobuffer.ResponseCodeResCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ResponseCode) Reset()         { *m = ResponseCode{} }
func (m *ResponseCode) String() string { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()    {}
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbb99ad2cb96e3c2, []int{0}
}

func (m *ResponseCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCode.Unmarshal(m, b)
}
func (m *ResponseCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCode.Marshal(b, m, deterministic)
}
func (m *ResponseCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCode.Merge(m, src)
}
func (m *ResponseCode) XXX_Size() int {
	return xxx_messageInfo_ResponseCode.Size(m)
}
func (m *ResponseCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCode proto.InternalMessageInfo

func (m *ResponseCode) GetCode() ResponseCodeResCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_UNKNOWN
}

func init() {
	proto.RegisterEnum("com.bc.protocol.protobuffer.ResponseCodeResCode", ResponseCodeResCode_name, ResponseCodeResCode_value)
	proto.RegisterType((*ResponseCode)(nil), "com.bc.protocol.protobuffer.response_code")
}

func init() { proto.RegisterFile("protocol_code.proto", fileDescriptor_cbb99ad2cb96e3c2) }

var fileDescriptor_cbb99ad2cb96e3c2 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0x89, 0x4f, 0xce, 0x4f, 0x49, 0xd5, 0x03, 0xf3, 0x84, 0xa4, 0x93, 0xf3,
	0x73, 0xf5, 0x92, 0x92, 0xf5, 0x60, 0x72, 0x10, 0x46, 0x52, 0x69, 0x5a, 0x5a, 0x6a, 0x91, 0xd2,
	0x44, 0x46, 0x2e, 0xde, 0xa2, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xb0, 0x26, 0x21, 0x77,
	0x2e, 0x16, 0x10, 0x2d, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x64, 0xac, 0x87, 0x47, 0xb7, 0x1e,
	0x8a, 0x4e, 0x10, 0x0f, 0xcc, 0x08, 0x02, 0x1b, 0xa0, 0x64, 0xce, 0xc5, 0x01, 0x13, 0x11, 0xe2,
	0xe6, 0x62, 0x0f, 0xf5, 0xf3, 0xf6, 0xf3, 0x0f, 0xf7, 0x13, 0x60, 0x10, 0xe2, 0xe6, 0x62, 0x0b,
	0x0e, 0x75, 0x76, 0x0d, 0x0e, 0x16, 0x38, 0xc1, 0x28, 0x24, 0xc8, 0xc5, 0x13, 0xea, 0xe7, 0x18,
	0x1a, 0xe2, 0xe1, 0x1f, 0xe4, 0x19, 0xe5, 0xea, 0x22, 0x30, 0x91, 0x39, 0x89, 0x0d, 0x6c, 0x85,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x6f, 0x7a, 0xb0, 0xce, 0x00, 0x00, 0x00,
}
