// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_info.proto

package com_bc_user_protobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfoSexType int32

const (
	UserInfo_MAN     UserInfoSexType = 0
	UserInfo_WOMAN   UserInfoSexType = 1
	UserInfo_UNKNOWN UserInfoSexType = 2
)

var UserInfoSexType_name = map[int32]string{
	0: "MAN",
	1: "WOMAN",
	2: "UNKNOWN",
}

var UserInfoSexType_value = map[string]int32{
	"MAN":     0,
	"WOMAN":   1,
	"UNKNOWN": 2,
}

func (x UserInfoSexType) String() string {
	return proto.EnumName(UserInfoSexType_name, int32(x))
}

func (UserInfoSexType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{0, 0}
}

type UserInfo struct {
	PhoneNumber          string          `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Id                   string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	NickName             string          `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Remarks              string          `protobuf:"bytes,4,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Sex                  UserInfoSexType `protobuf:"varint,5,opt,name=sex,proto3,enum=com.bc.user.protobuffer.UserInfoSexType" json:"sex,omitempty"`
	Avatar               string          `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Adress               *UserInfoRegion `protobuf:"bytes,7,opt,name=adress,proto3" json:"adress,omitempty"`
	PerSignature         string          `protobuf:"bytes,8,opt,name=per_signature,json=perSignature,proto3" json:"per_signature,omitempty"`
	QrCode               string          `protobuf:"bytes,9,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfo) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *UserInfo) GetSex() UserInfoSexType {
	if m != nil {
		return m.Sex
	}
	return UserInfo_MAN
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetAdress() *UserInfoRegion {
	if m != nil {
		return m.Adress
	}
	return nil
}

func (m *UserInfo) GetPerSignature() string {
	if m != nil {
		return m.PerSignature
	}
	return ""
}

func (m *UserInfo) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

type UserInfoRegion struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRegion) Reset()         { *m = UserInfoRegion{} }
func (m *UserInfoRegion) String() string { return proto.CompactTextString(m) }
func (*UserInfoRegion) ProtoMessage()    {}
func (*UserInfoRegion) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{0, 0}
}

func (m *UserInfoRegion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRegion.Unmarshal(m, b)
}
func (m *UserInfoRegion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRegion.Marshal(b, m, deterministic)
}
func (m *UserInfoRegion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRegion.Merge(m, src)
}
func (m *UserInfoRegion) XXX_Size() int {
	return xxx_messageInfo_UserInfoRegion.Size(m)
}
func (m *UserInfoRegion) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRegion.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRegion proto.InternalMessageInfo

func (m *UserInfoRegion) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *UserInfoRegion) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

//请求个人信息
type RequestUserInfo struct {
	Token                *UserToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string     `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestUserInfo) Reset()         { *m = RequestUserInfo{} }
func (m *RequestUserInfo) String() string { return proto.CompactTextString(m) }
func (*RequestUserInfo) ProtoMessage()    {}
func (*RequestUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{1}
}

func (m *RequestUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUserInfo.Unmarshal(m, b)
}
func (m *RequestUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUserInfo.Marshal(b, m, deterministic)
}
func (m *RequestUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUserInfo.Merge(m, src)
}
func (m *RequestUserInfo) XXX_Size() int {
	return xxx_messageInfo_RequestUserInfo.Size(m)
}
func (m *RequestUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUserInfo proto.InternalMessageInfo

func (m *RequestUserInfo) GetToken() *UserToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *RequestUserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

//响应个人信息
type ResponseUserInfo struct {
	Code                 *ResponseCode `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId               *UserInfo     `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseUserInfo) Reset()         { *m = ResponseUserInfo{} }
func (m *ResponseUserInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseUserInfo) ProtoMessage()    {}
func (*ResponseUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{2}
}

func (m *ResponseUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUserInfo.Unmarshal(m, b)
}
func (m *ResponseUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUserInfo.Marshal(b, m, deterministic)
}
func (m *ResponseUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUserInfo.Merge(m, src)
}
func (m *ResponseUserInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseUserInfo.Size(m)
}
func (m *ResponseUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUserInfo proto.InternalMessageInfo

func (m *ResponseUserInfo) GetCode() *ResponseCode {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ResponseUserInfo) GetUserId() *UserInfo {
	if m != nil {
		return m.UserId
	}
	return nil
}

func init() {
	proto.RegisterEnum("com.bc.user.protobuffer.UserInfoSexType", UserInfoSexType_name, UserInfoSexType_value)
	proto.RegisterType((*UserInfo)(nil), "com.bc.user.protobuffer.user_info")
	proto.RegisterType((*UserInfoRegion)(nil), "com.bc.user.protobuffer.user_info.region")
	proto.RegisterType((*RequestUserInfo)(nil), "com.bc.user.protobuffer.request_user_info")
	proto.RegisterType((*ResponseUserInfo)(nil), "com.bc.user.protobuffer.response_user_info")
}

func init() { proto.RegisterFile("user_info.proto", fileDescriptor_84fe32b1d3884b9c) }

var fileDescriptor_84fe32b1d3884b9c = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xf9, 0xb0, 0xe3, 0x71, 0x29, 0x65, 0x90, 0xe8, 0x2a, 0x5c, 0x82, 0xe1, 0x10, 0xa8,
	0xe4, 0x43, 0x90, 0x38, 0x80, 0x40, 0xaa, 0x38, 0x21, 0x84, 0x2b, 0x19, 0xa1, 0x1e, 0xad, 0x8d,
	0x3d, 0x49, 0xad, 0xd4, 0xbb, 0xce, 0xee, 0x1a, 0x35, 0x3f, 0x83, 0xbf, 0xc2, 0x2f, 0x44, 0x5e,
	0x67, 0x5b, 0x22, 0x84, 0xe8, 0xc9, 0x3b, 0x6f, 0xfc, 0xde, 0xdb, 0x37, 0xb3, 0xf0, 0xa8, 0xd5,
	0xa4, 0xf2, 0x4a, 0xac, 0x64, 0xd2, 0x28, 0x69, 0x24, 0x9e, 0x16, 0xb2, 0x4e, 0x96, 0x45, 0xd2,
	0xe1, 0x3d, 0xb4, 0x6c, 0x57, 0x2b, 0x52, 0x53, 0xbc, 0x96, 0xeb, 0x4a, 0xe4, 0xda, 0x70, 0xd3,
	0xea, 0xbe, 0x33, 0x7d, 0x62, 0x3f, 0x85, 0xbc, 0xce, 0x0b, 0x59, 0x52, 0x0f, 0xc6, 0xbf, 0x86,
	0x10, 0xde, 0xaa, 0xe2, 0x73, 0x38, 0x6a, 0xae, 0xa4, 0xa0, 0x5c, 0xb4, 0xf5, 0x92, 0x14, 0xf3,
	0x66, 0xde, 0x3c, 0xcc, 0x22, 0x8b, 0xa5, 0x16, 0xc2, 0x63, 0x18, 0x54, 0x25, 0x1b, 0xd8, 0xc6,
	0xa0, 0x2a, 0xf1, 0x19, 0x84, 0xa2, 0x2a, 0x36, 0xb9, 0xe0, 0x35, 0xb1, 0xa1, 0x85, 0x27, 0x1d,
	0x90, 0xf2, 0x9a, 0x90, 0x41, 0xa0, 0xa8, 0xe6, 0x6a, 0xa3, 0xd9, 0xc8, 0xb6, 0x5c, 0x89, 0x1f,
	0x60, 0xa8, 0xe9, 0x86, 0x8d, 0x67, 0xde, 0xfc, 0x78, 0x71, 0x96, 0xfc, 0x23, 0x47, 0x72, 0x17,
	0x58, 0xd3, 0x4d, 0x6e, 0x76, 0x0d, 0x65, 0x1d, 0x0f, 0x9f, 0x82, 0xcf, 0x7f, 0x70, 0xc3, 0x15,
	0xf3, 0xad, 0xee, 0xbe, 0xc2, 0x73, 0xf0, 0x79, 0xa9, 0x48, 0x6b, 0x16, 0xcc, 0xbc, 0x79, 0xb4,
	0x78, 0x75, 0x0f, 0x65, 0x45, 0xeb, 0x4a, 0x8a, 0x6c, 0x4f, 0xc4, 0x17, 0xf0, 0xb0, 0x21, 0x95,
	0xeb, 0x6a, 0x2d, 0xb8, 0x69, 0x15, 0xb1, 0x89, 0x75, 0x38, 0x6a, 0x48, 0x7d, 0x73, 0x18, 0x9e,
	0x42, 0xb0, 0x55, 0x76, 0x8e, 0x2c, 0xec, 0x2f, 0xb0, 0x55, 0x9f, 0x64, 0x49, 0xd3, 0xb7, 0xe0,
	0xf7, 0x7a, 0x5d, 0xf6, 0x42, 0xb6, 0xc2, 0xa8, 0xdd, 0x7e, 0x8c, 0xae, 0x44, 0x84, 0x51, 0x51,
	0x99, 0xdd, 0x7e, 0x88, 0xf6, 0x1c, 0x9f, 0xc1, 0xc4, 0x25, 0xc4, 0x00, 0x86, 0x5f, 0xcf, 0xd3,
	0x93, 0x07, 0x18, 0xc2, 0xf8, 0xf2, 0xa2, 0x3b, 0x7a, 0x18, 0x41, 0xf0, 0x3d, 0xfd, 0x92, 0x5e,
	0x5c, 0xa6, 0x27, 0x83, 0xf8, 0x0a, 0x1e, 0x2b, 0xda, 0xb6, 0xa4, 0x4d, 0x7e, 0xb7, 0xbb, 0x77,
	0x30, 0x36, 0x72, 0x43, 0xc2, 0xba, 0x45, 0x8b, 0x97, 0x2e, 0xb9, 0x7d, 0x09, 0x7f, 0x47, 0xb7,
	0xff, 0x66, 0x3d, 0xa5, 0x8b, 0xd3, 0x0b, 0xb9, 0xcd, 0xfa, 0x5d, 0xf9, 0xb9, 0x8c, 0x7f, 0x7a,
	0x80, 0x8a, 0x74, 0x23, 0x85, 0xa6, 0x3f, 0xbc, 0x3e, 0xc2, 0xc8, 0x66, 0xef, 0xad, 0x5e, 0x3b,
	0x2b, 0xf7, 0xc0, 0x0e, 0xdc, 0x6e, 0xe9, 0x1d, 0x23, 0xb3, 0x3c, 0x7c, 0x7f, 0xe8, 0x17, 0x2d,
	0xe2, 0xff, 0xef, 0xc9, 0xdd, 0x69, 0xe9, 0xdb, 0xf6, 0x9b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x20, 0xcc, 0xf9, 0x57, 0x0e, 0x03, 0x00, 0x00,
}
